apiVersion: v1
kind: Secret
metadata:
  name: env-vars
  namespace: contract-manager
type: Opaque
data:
  MONGO_URL: {{ .Values.env.MONGO_URL | b64enc }}
  MONGO_TEST_URL: {{ .Values.env.MONGO_TEST_URL | b64enc }}
  MONGO_USERNAME: {{ .Values.env.MONGO_USERNAME | b64enc }}
  MONGO_PASSWORD: {{ .Values.env.MONGO_PASSWORD | b64enc }}
  SERVER_PORT: {{ .Values.env.SERVER_PORT | b64enc }}
  SECRET_AUTH_KEY: {{ .Values.env.SECRET_AUTH_KEY | b64enc }}
  SECRET_SESSION_KEY: {{ .Values.env.SECRET_SESSION_KEY | b64enc }}
  CATALOG_REGISTRY_URL: {{ .Values.env.CATALOG_REGISTRY_URL | b64enc }}
  SERVER_BASE_URL: {{ .Values.env.SERVER_BASE_URL | b64enc }}
