apiVersion: v1
kind: Service
metadata:
  name: contract-manager
  namespace: contract-manager
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: contract-manager
